dist: focal
language: node_js
node_js:
- 14

env:
- SLS_DEBUG=* TWITTER_SCREEN_NAME=this_vid EXTERNAL_URL=thisvid.space FIREBASE_PROJECT_ID=downloadthisvideo-662ae TWITTER_CALLBACK_URL="https://thisvid.space/_/completetwittersignin"

cache:
  directories:
  - node_modules

install: NODE_ENV=development npm i && npm i -g serverless

stages:
- name: predeploy
- name: deploy
  if: branch = master

jobs:
  include:
  - stage: deploy
    script: 
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - sudo ./aws/install
    - |
      aws --region us-east-1 s3 cp \
      s3://shalvah-creds/downloadthisvideo-serviceaccount.json  \
      ./downloadthisvideo-serviceaccount.json && \
      aws --region us-east-1 s3 cp \
      s3://shalvah-creds/thisvid-analytics-serviceaccount.json  \
      ./thisvid-analytics-serviceaccount.json && \
      NODE_ENV=production sls deploy

  - stage: predeploy
    name: Test
    script: NODE_ENV=development npm run test

  - stage: predeploy
    name: Lint
    script: npm run lint
