name: Deploy

on:
  workflow_run:
    workflows: ["Checks"]
    branches: [master]
    types:
      - completed
  push:
    branches: [master]

env:
  NODE_ENV: production
  SLS_DEBUG: "*"
  TWITTER_SCREEN_NAME: this_vid
  EXTERNAL_URL: thisvid.space
  FIREBASE_PROJECT_ID: downloadthisvideo-662ae
  TWITTER_CALLBACK_URL: "https://thisvid.space/_/completetwittersignin"

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    name: Deploy to prod
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.18.0
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.0
      - run: npm ci --include=dev
      - run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --region us-east-1 s3 cp \
            s3://shalvah-creds/downloadthisvideo-serviceaccount.json  \
            ./downloadthisvideo-serviceaccount.json && \
            aws --region us-east-1 s3 cp \
            s3://shalvah-creds/thisvid-analytics-serviceaccount.json  \
            ./thisvid-analytics-serviceaccount.json && sls deploy